services:
  - type: web
    name: email-marketing-platform
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: DATABASE_URL
        fromDatabase:
          name: email_marketing_db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: BREVO_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false

databases:
  - name: email_marketing_db
    databaseName: email_marketing
    user: email_marketing_user
    plan: free