theme: jekyll-theme-minimal
title: Email Campaign Manager
description: Comprehensive Email Marketing Platform
logo: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
repository_url: https://github.com/narendrancs89/EmailCampaignManager
